name: flyer_chat_image_message
version: 3.10.1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  cross_file: ^0.3.3+6
  crypto: ^3.0.3
  flutter:
    sdk: flutter
  flutter_chat_core: ^3.10.1
  http: ^1.1.0
  mime: ^1.0.4
  path_provider: ^2.1.1
  provider: ^6.0.5
  thumbhash: ^0.1.0+1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
